{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.TaskMethodThatThrows()
at VerifyTests.InnerVerifier.<ThrowsTask>d__20.MoveNext()
}